# Generated by Django 2.2.7 on 2019-11-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test1122',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbb', models.DateField()),
                ('aaa', models.CharField(max_length=20)),
            ],
        ),
    ]
