# Generated by Django 2.2.7 on 2019-12-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
