# Generated by Django 2.2.7 on 2019-12-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_contact_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fristName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('instrument', models.IntegerField()),
            ],
        ),
    ]
