# Generated by Django 2.2.7 on 2019-12-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_musician'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
