# Generated by Django 2.2.7 on 2019-12-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_musician'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musician',
            new_name='Musicians',
        ),
    ]
