# Generated by Django 2.2.7 on 2019-12-06 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=2018, on_delete=django.db.models.deletion.CASCADE, to='books.Publisher'),
            preserve_default=False,
        ),
    ]
