# Generated by Django 2.2.7 on 2020-02-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.CharField(max_length=50)),
                ('StudentName', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
